# Generated by Django 2.0.2 on 2018-09-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('up_heading', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('down_heading', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
