# Generated by Django 2.0.2 on 2018-09-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_icon', models.ImageField(blank=True, default='ServiceIcon/settings.png', upload_to='ServiceIcon/')),
                ('s_title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('s_details', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
