# Generated by Django 2.0.2 on 2018-09-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_home_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='sub_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='about me', max_length=25),
        ),
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
