# Generated by Django 2.0.2 on 2018-09-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180909_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='cv',
            field=models.FileField(default='About/NID-card.pdf', upload_to='About/'),
        ),
    ]
