# Generated by Django 2.0.2 on 2018-09-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180909_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleSubtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(blank=True, default='about me', max_length=25, null=True)),
                ('about_sub_title', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('service_title', models.CharField(blank=True, default='services', max_length=25, null=True)),
                ('service_sub_title', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('portfolio_title', models.CharField(blank=True, default='portfolio', max_length=25, null=True)),
                ('portfolio_sub_title', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('feedback_title', models.CharField(blank=True, default='feedback', max_length=25, null=True)),
                ('feedback_sub_title', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('contact_title', models.CharField(blank=True, default='contact me', max_length=25, null=True)),
                ('contact_sub_title', models.CharField(blank=True, default='', max_length=25, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
    ]
