# Generated by Django 2.0.2 on 2018-09-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180909_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlesubtitle',
            name='about_sub_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='titlesubtitle',
            name='contact_sub_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='titlesubtitle',
            name='feedback_sub_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='titlesubtitle',
            name='portfolio_sub_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='titlesubtitle',
            name='service_sub_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
