# Generated by Django 2.0.2 on 2018-09-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180909_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/', max_length=255, null=True)),
                ('twitter_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('twitter_url', models.URLField(blank=True, default='https://www.twitter.com/', max_length=255, null=True)),
                ('linkedin_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('linkedin_url', models.URLField(blank=True, default='https://www.linkedin.com/', max_length=255, null=True)),
                ('google_plus_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('google_plus_url', models.URLField(blank=True, default='https://plus.google.com/', max_length=255, null=True)),
            ],
        ),
    ]
