# Generated by Django 2.0.2 on 2018-09-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20180912_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='s_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
