# Generated by Django 2.0.2 on 2018-10-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20180914_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
